<a href="https://colab.research.google.com/github/purvaaasare8-ctrl/machine-learning/blob/main/project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving sample.csv to sample.csv

In [ ]:
import pandas as pd

df = pd.read_csv("sample.csv", header=0)

In [ ]:
X = df.drop("Cost Price", axis=1)

y = df["Cost Price"]

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (47, 7)
Shape of y: (47,)

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("/content/sample.csv").iloc[1:]

numerical_cols = ['Opening', 'Purchase/', 'Number of', 'Hand-In-', 'Cost Price.1']
df[numerical_cols] = df[numerical_cols].apply(pd.to_numeric)

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[numerical_cols])

scaled_df = pd.DataFrame(scaled_data, columns=numerical_cols)

print("Scaled Data Head:")
display(scaled_df.head())

Scaled Data Head:

    Opening  Purchase/  Number of  Hand-In-  Cost Price.1
0  1.085107   0.777222   0.827571  1.043733      4.099047
1  0.311232  -0.062032  -0.476137  0.408657      1.097211
2  1.858982   1.616476   2.131278  1.678809     -0.275969
3 -0.462642  -0.901286  -0.997620 -0.416941     -0.263195
4  2.632856   2.455730   3.434986  2.313884      4.099047

In [ ]:
categorical_cols = X.select_dtypes(include="object").columns

X_encoded = pd.get_dummies(X, columns=categorical_cols)
X_encoded = X_encoded.astype(int)

print(X_encoded.head())

   Product ID_P101  Product ID_P102  Product ID_P103  Product ID_P104  \
0                0                0                0                0
1                1                0                0                0
2                0                1                0                0
3                0                0                1                0
4                0                0                0                1

   Product ID_P105  Product ID_P106  Product ID_P107  Product ID_P108  \
0                0                0                0                0
1                0                0                0                0
2                0                0                0                0
3                0                0                0                0
4                0                0                0                0

   Product ID_P109  Product ID_P110  ...  Cost Price.1_6400  \
0                0                0  ...                  0
1                0                0  ...                  0
2                0                0  ...                  0
3                0                0  ...                  0
4                0                0  ...                  0

   Cost Price.1_6840  Cost Price.1_72000  Cost Price.1_740  Cost Price.1_750  \
0                  0                   0                 0                 0
1                  0                   1                 0                 0
2                  0                   0                 0                 0
3                  0                   0                 0                 0
4                  0                   0                 0                 0

   Cost Price.1_780  Cost Price.1_840  Cost Price.1_850  Cost Price.1_9750  \
0                 0                 0                 0                  0
1                 0                 0                 0                  0
2                 0                 0                 0                  0
3                 0                 0                 0                  0
4                 0                 0                 0                  0

   Cost Price.1_Total (USD)
0                         1
1                         0
2                         0
3                         0
4                         0

[5 rows x 206 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

cols = ['Opening', 'Purchase/', 'Number of', 'Hand-In-']

data = X.iloc[1:].copy()
data[cols] = data[cols].astype(float)

scaler = StandardScaler()
data[cols] = scaler.fit_transform(data[cols])

print("Data scaled successfully:")
display(data[cols].head())

Data scaled successfully:

    Opening  Purchase/  Number of  Hand-In-
1  1.085107   0.777222   0.827571  1.043733
2  0.311232  -0.062032  -0.476137  0.408657
3  1.858982   1.616476   2.131278  1.678809
4 -0.462642  -0.901286  -0.997620 -0.416941
5  2.632856   2.455730   3.434986  2.313884

In [ ]:
from sklearn.model_selection import train_test_split

y_clean = y.iloc[1:]

X_train, X_test, y_train, y_test = train_test_split(
    data,
    y_clean,
    test_size=0.33,
    random_state=42
)

print(f"X shape: {data.shape}")
print(f"y shape: {y_clean.shape}")
print("Split successful!")

X shape: (46, 7)
y shape: (46,)
Split successful!

In [ ]:
from sklearn.linear_model import LinearRegression

X_train_numeric = X_train.drop(columns=['Product ID', 'Product Name'])

model = LinearRegression()

model.fit(X_train_numeric, y_train.astype(float))

print("Model trained successfully!")
print("Intercept:", model.intercept_)
print("Coefficients:")
for col, coef in zip(X_train_numeric.columns, model.coef_):
    print(f"{col}: {coef}")

Model trained successfully!
Intercept: 21.110105698727637
Coefficients:
Opening: -65.03705541788864
Purchase/: 6.046782251895574
Number of: 17.738236277902306
Hand-In-: 9.291039195730193
Cost Price.1: 0.018103261680902705

In [ ]:
X_test_numeric = X_test.drop(columns=['Product ID', 'Product Name'])

y_pred = model.predict(X_test_numeric)

print("Predicted Values:")
print(y_pred[:10])

print("\nActual Values:")
print(y_test.iloc[:10].values.astype(float))

Predicted Values:
[  10.54675617  117.58588517   30.57204678  -15.58599967   94.57692578
   77.98143768 1250.58996716   18.51988903   88.40472888   91.16137288]

Actual Values:
[ 15. 120.  60.   8.  50.  15. 900.  20.  80. 100.]

In [ ]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

if r2 >= 0.8:
    print("The model performs very well.")
elif r2 >= 0.6:
    print("The model performs well.")
else:
    print("The model needs improvement.")

R² Score: 0.808545449428324
The model performs very well.

In [ ]:
import joblib

joblib.dump(model, "LR_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X_encoded.columns.tolist(), "columns.pkl")

print("Files saved successfully.")

Files saved successfully.

### Consolidated Error-Free Program
This version handles the data cleaning, feature scaling, and model training in one flow using the correct column names.